# Python Crash Course

*(Compiled from various sources on the internet by HK Tan and myself)*



---


## Quick note about Jupyter

This document is a Jupyter notebook. A Jupyter notebook consists of **text** cells and/or **code** cells. 

**Text cells** consists of instruction text while **code cells** contains Python codes.

You can run a code cell by moving the cursor to the cell's left-hand side. A run button  ![代替テキスト](https://raw.githubusercontent.com/kalngyk/repoman/master/run.png) will appear. Clicking on the "run" button executes the cell. After that, the run button turns into a stop button ![代替テキスト](https://raw.githubusercontent.com/kalngyk/repoman/master/stop.png) -- clicking on the stop button will interrupt the cell's execution. When the execution ends, the stop button turns back into a run button. If the execution runs into problem, the stop cursor will turn into a red-colored run button ![代替テキスト](https://raw.githubusercontent.com/kalngyk/repoman/master/error.png) to indicate that the execution failed.

*Tips: While your cursor is within a code cell, you can run the cell by pressing **`<Shift>+<Enter>`** instead of clicking the run button.*

The output messages of a code cell is shown immediately below the cell. You can clear the output messages of a cell by right-clicking over the "run" button and selecting **"Clear output"**. The menu which shows up when you right-click over the "run" button also allows you to delete the associated cell.

To create a new cell or reposition a cell, use the menu at the top of the page: ![代替テキスト](https://raw.githubusercontent.com/kalngyk/repoman/master/menubar.png).

*Tips: Pressing* **`<Control>+<s>`** *saves changes you have made to the notebook immediately.*

## Quick note about Google Colab

This Jupyter notebook runs on Google Colab, a free cloud platform for running Python codes with **GPU support**. To enable/disable GPU for a notebook, go to the top menu and choose "**Edit**> **Notebook Settings**> **Hardware Accelarator**".

When a colab session is first started, a VM (virtual machine) is assigned to the session to store your files as well as execute your codes. However, each session lasts only for 12 hours. When the session ends, your variables and files created during the session is deleted. While you can continue to work by restarting a new session, you will need to restore your variables and files. To save those data across different sessions, you are advised to carefully output them to your local drive or to Google Drive.



---

# Section 1: Operators and variables

## Arithmetic operators
The Python interpreter can be used to evaluate expressions, for example simple arithmetic expressions.

In [1]:
# This is a comment
1 + 1   # addition operation

2

In [2]:
2 * 3   # multiplication operaiton

6

In [3]:
11 / 3  # Normal division

3.6666666666666665

In [4]:
11 // 3 # integer division

3

In [5]:
11 % 3  # modulus operation

2

In [6]:
2 ** 3  # exponent operation

8

Boolean operators also exist in Python to manipulate the primitive True and False values.

In [7]:
1 == 0

False

In [8]:
not (1 == 0)

True

In [9]:
(2 == 2) and (2 == 3)

False

In [10]:
(2 == 2) or (2 == 3)

True

## Variables

We can also store expressions into variables. Here are some important rules about using variables in Python:

You do not have to perform variable declaration, but a variable must be created before it can be used. (In Jupyter notebook, the variables created by running a code cell is immediately available in other code cells.)

The type of a variable is automatically determined based on the value assigned.



In [11]:
s = 'hello world'   # defining a variable
print(s)
print(type(s))

hello world
<class 'str'>


In the above code, we use `type` to display the type of `s`. Since 'hello world' is a string, the variable `s` is of type string.

In [12]:
fval = 7.3   # this will create a floating point variable
print(fval)
print(type(fval))

7.3
<class 'float'>


In [13]:
ival = 12    # this will create an integer variable
print(ival)
print(type(ival))

12
<class 'int'>


In [14]:
fval += 2.5  # operate on fval
print(fval)  # you can print the content of a variable  using print command

9.8


In [15]:
ival += 3    
ival         # you can display the value of a variable by typing the variable name

15

Remember that you cannot use a variable that you have not created. The following command will generate an error  because `var` has not been created.

In [16]:
print(var)   # we have not defined a variable called var! This will generate an error!

NameError: ignored

## Importing libraries (modules)
One reason for the popularity of Python is the large number of libraries (called modules) available for the language.

To use a module, use the keyword `import`.

The following codes import the math module, which enables you to use mathematical functions such as π (pi) and sine, cosine and tangent.

In [ ]:
import math

In [18]:
print ('The sin of 90 degrees is', math.sin(math.pi/2))

The sin of 90 degrees is 1.0


In [19]:
print ('log of 100 is ', math.log(100))

log of 100 is  4.605170185988092


If we are only interested in a particular function (or class) from a module, for example, if we only need `sqrt` from the `math` module, we may write the following:

In [20]:
from math import sqrt
sqrt(2)

1.4142135623730951

## The `string` class

Like C++ and Java, Python has a built in string type. A `string` object can be defined with either a single quote (`'`)  or double quote (`"`). 

In [ ]:
s = 'hot'

In [ ]:
s = s + 'dog' # or s += 'dog'

In [24]:
s             # display the value of the string object

'hotdog'

In [25]:
print(s)      # printing the string object

hotdog


Python is object-oriented. To show this let us consider the `string` class in the following codes.

*(To see the list of functions provided by a class, type the object variable name and then press TAB. For example, typing  `s.<TAB>` will pop up a menu which shows the list of functions for the class.)*



In [26]:
s = 'HELP'
s.lower()

'help'

In [27]:
'help'.upper()

'HELP'

To get the length of a string, you can use the `len` command.

In [28]:
len('Help')

4

You can also use the command `help` to get help on commands.

In [29]:
help(s.find)

Help on built-in function find:

find(...) method of builtins.str instance
    S.find(sub[, start[, end]]) -> int
    
    Return the lowest index in S where substring sub is found,
    such that sub is contained within S[start:end].  Optional
    arguments start and end are interpreted as in slice notation.
    
    Return -1 on failure.



## Printing to screen

The standard way for showing output messages is through the function `print`.

In [30]:
a = 3
print('There are', a, 'people in the meeting')

There are 3 people in the meeting


You can format output using the `str.format()` method where we use the curly braces `{}` as placeholders.  

In the following example, the first bracket `{}` would be replaced by `x` and the second by `y`. 

In [31]:
x = 5; y = 10
print('The value of x is {} and y is {}'.format(x,y))

The value of x is 5 and y is 10


We can also specify *the order* in which it is printed by using numbers (tuple index).

In the following example, the placeholder `{0}` would be replaced by the first parameter `bread` regardless of its position in the `print` statement. Similarly for the placeholder `{1}`. 

In [32]:
print('I love {0} and {1}'.format('bread', 'butter'))
print('I love {1} and {0}'.format('bread', 'butter'))  # changing the order

I love bread and butter
I love butter and bread


Formatting of integer values can be done as in the following example, where
* `d` specifies that the placedholder is to be replaced by an *integer*. 
* `6` specifies that a total of 6 characters would be allocated to print out the integer.

In [33]:
print('Integer value is {:d}.'.format(23))
print('Integer value is {:6d}.'.format(23))

Integer value is 23.
Integer value is     23.


Formatting of floating point values can be done as in the following example, where
* `f`  specifies that the placedholder is to be replaced by an *real number*. 
* `6` specifies that a total of 6 characters would be allocated to print out the number. 
* `.2` displays the real number up to two decimal places
* `0` specifies that if the number of characters is less than number of allocated characters (6 in our case), the empty spaces should be replaced with 0.

In [34]:
print('The float value is {:f}'.format(3.141592653589793))
print('The float value is {:06.2f}'.format(3.141592653589793))
print('The float value is {:6.2f}'.format(3.141592653589793))

The float value is 3.141593
The float value is 003.14
The float value is   3.14


---
# Section 2: Functions and control structures

## Functions
Python functions are defined similar to other languages such as C and Java. **However, blocks of codes in Python are organized by how they are indented.** 

While in languages such as C/C++, Java, JavaScript, C#, Perl, and R, codes are placed within curly brackets (`{}`) to form a block,
in Python, codes are considered to be in the same block if they are indented by the same amount of space from the left (unless broken by a higher level block). The figure below gives a simple, easy-to-understand example.

![代替テキスト](https://raw.githubusercontent.com/kalngyk/repoman/master/indentation.png)

These indentations can be written with spaces or tabs, but the same spaces/tabs must be consistently used for all the codes in the same block.

Another important thing to take note is that unlike in other languages, **statements in Python do not end in '`;`'**.





In [ ]:
# Correct way of defining a function
def square(num):  
    "Returns the square of a number"
    result = num**2
    return result

**Note that the function definition ends with a ':' character.**
Now that we have defined our function `square`, we can make use of the function to square some numbers.

In [36]:
x = square(2)
print("{0} times {0} equals {1}".format(2, x))
x = square(2.5)
print("{0}{0} equals {1}".format(2.5, x))

2 times 2 equals 4
2.52.5 equals 6.25


The following codes would result in an **IndentationError** since Python does not use curly bracket to define the code block.

In [37]:
# this will not work. 

def square(num):
{
   result = num**2
   return result
}

IndentationError: ignored

The following codes would result in an **IndentationError** as well.

In [38]:
# This will NOT work.

def square(num):
    result = num**2
return result

SyntaxError: ignored

### Functions returning more than one variable

Different from most languages, Python functions are allowed to return more than one variable.

In [ ]:
def get_square_n_cube(num):
    "Returns the square of a number"
    sq = num**2
    cb = num**3
    return sq, cb

In [40]:
sq, cb = get_square_n_cube(2)
print(sq, cb)

4 8


Variables returned from a function can be selectively ignored, as follows.

In [41]:
sq, _ = get_square_n_cube(2)   # ignore the cube
print(sq)

4


### Function parameter passing
Same as with other languages,  in Python, objects are passed by reference, while **primitive variables** such as `integer`, `double` and `float` as well as **`string`s** are **passed by value**. For example, in the following code, changes to parameters `intval` and `strval` in `func` will not affect the original two variables. 

In [ ]:
def func(intval, strval):
    intval = 100
    strval = "Modified string value"
    print (">>> func: numval = {}, strval = {}".format(intval, strval))

In [43]:
intval  = 0
strval = "Original string value"

print ("main (before calling func): numval = {}, strval = {}".format(intval, strval))
func(intval, strval)
print ("main (after calling func): numval = {}, strval = {}".format(intval, strval))


main (before calling func): numval = 0, strval = Original string value
>>> func: numval = 100, strval = Modified string value
main (after calling func): numval = 0, strval = Original string value


### Function default arguments

Python allows the setting of default arguments in the list of input parameters -- these values will be used when the caller does not specify the values for these parameters.

We show this with the following function, which also uses an `if` statement. In Python, an `if` statement must end with the "`:`" character, and the entire block of codes to be executed must be indented further to the right.



In [ ]:
def square(num, rounding=False):
    result = num**2
    if rounding:
        result = int(result)
    return result

In [45]:
print(square(2.5))
print(square(2.5, rounding=True))
print(square(2.5, True))

6.25
6
6


## Conditional operators
Python only allows the conditional operators: `if` and `elif`. There is no `switch-case` operator in Python.

The following code shows the syntax for implementing compound conditions in Python.

In [46]:
from random import random

if random() > .5 and random() > .5:
    print('This line gets printed 1/4 of the time')
else:
    print('This line gets printed 3/4 of the time')

This line gets printed 3/4 of the time


In [47]:
from random import random

if random() > .5 or random() > .5:
    print('This line gets printed 3/4 of the time')
else:
    print('This line gets printed 1/4 of the time')

This line gets printed 3/4 of the time


## Loops

The operator for performing loops in Python is `for` and `while`. Similarly, indentation is used to define the scope for loops. The following example show how to use the `for` loop to iterate a list of integers and strings

In [48]:
for num in [1, 2, 3, 4, 5]:
    print(num)

1
2
3
4
5


In [49]:
for name in ['lessie', 'joe', 'bob']:
    print(name)

lessie
joe
bob


In [50]:
num = 1
while num <= 5:
    print(num)
    num += 1

1
2
3
4
5


You can use the function **`range(end)`** to generate  an iterable sequence of integers starting from 0 up to not including `end`.

In [51]:
for num in range(5):        
    print(num) 

0
1
2
3
4


You can use the function **`range(start, end)`** to generate  an iterable sequence of integers starting from `start` up to `end-1`.

In [52]:
for num in range(3, 7):     
    print(num) 

3
4
5
6


You can use the function **`range(start, end, skip)`** to generate an iterable sequence of integers starting from start up to end-1 with a resolution of `skip` .

In [53]:
for num in range(10, 26, 5):  
    print(num) 

10
15
20
25


When looping a sequence, the position index and corresponding value can be retrieved using the **`enumerate()`** function.

In [54]:
for i, v in enumerate(['tic', 'tac', 'toe']):
    print(i, v)

0 tic
1 tac
2 toe


To loop over two or more sequences at the same time, the entries can be paired using the **`zip()`** function.

In [55]:
questions = ['name', 'quest', 'favorite color']
answers = ['lancelot', 'the holy grail', 'blue']
for q, a in zip(questions, answers):
    print ('What is your {0}?  It is {1}.'.format(q, a))

What is your name?  It is lancelot.
What is your quest?  It is the holy grail.
What is your favorite color?  It is blue.


In [56]:
names = ['Krishnan', 'Shafie', 'Kim Loong']
grades = [99, 100, 89]

for n, g in zip(names, grades):
    print('{0}: {1}.'.format(n, g))

Krishnan: 99.
Shafie: 100.
Kim Loong: 89.


---
# Section 3: Built-in data structures

Python comes equipped with some useful built-in data structures. They include
* List
* Tuple
* Set
* Dictionary



## List

A list is the simplest, most flexible and arguably the most frequently used  data structure in Python. It stores a sequence of mutable (changeable) items of possibly different types.

**Create a new list**:

In [57]:
fruits = ['apple', 'orange', 'pear']   # a list of strings
print(fruits)

numbers = [11, 12, 13, 14]             # a list of integers
print(numbers)

isHandsome = [True, False, True]       # a list of booleans
print(isHandsome)

rojak = [11, 'hello', True, [1,2,3], ['one', 2, False]]     # a list of different types of items
print(rojak)

['apple', 'orange', 'pear']
[11, 12, 13, 14]
[True, False, True]
[11, 'hello', True, [1, 2, 3], ['one', 2, False]]


**Get the length of a list**:

In [58]:
len(numbers)   

4

**Iterate all items in a list**:

In [59]:
numbers = [11, 12, 13, 14]
for x in numbers:
    print(x)

11
12
13
14


**Unpack the values in a list into individual variables:** 

In [60]:
a, b, c = fruits
print(a)
print(b)
print(c)

apple
orange
pear


**Concatenate multiple lists**

Use the `+` operator to do list concatenation:

In [61]:
fruits = ['apple', 'orange', 'pear']
print(fruits)

otherFruits = ['kiwi', 'strawberry']
print(otherFruits)

allFruits = fruits + otherFruits
print(allFruits)

['apple', 'orange', 'pear']
['kiwi', 'strawberry']
['apple', 'orange', 'pear', 'kiwi', 'strawberry']


**Access a specific item in the list**:

In [62]:
fruits[0]            # first item of fruits

'apple'

In [63]:
fruits[0] = 'durian'
fruits

['durian', 'orange', 'pear']

In [64]:
rojak[3]

[1, 2, 3]

In [65]:
rojak[3] = 'new item'
rojak

[11, 'hello', True, 'new item', ['one', 2, False]]

**Slice indexing (creating a sublist):**

We can index multiple adjacent elements using the slice operator. For instance, `fruits[1:3]` returns a list containing the elements at position 1 and 2. In general `fruits[start:stop]` will get the elements in `start`, `start`+1, ..., `stop`-1. We can also do `fruits[start:]` which returns all elements starting from the start index. Also `fruits[:end]` will return all elements before the element at position end:

In [66]:
print(allFruits)    # print all items

print(allFruits[0:2])  # items 0 and 1 (not including 2)
print(allFruits[:3])   # first item to item 2 (not including 3)
print(allFruits[2:])   # items 2 to last item

['apple', 'orange', 'pear', 'kiwi', 'strawberry']
['apple', 'orange']
['apple', 'orange', 'pear']
['pear', 'kiwi', 'strawberry']


**Negative indexing:**

Python also allows negative-indexing from the back of the list. For instance, `allfruits[-1]` will access the last element `'strawberry'`:

In [67]:
print(allFruits)
allFruits[-1]

['apple', 'orange', 'pear', 'kiwi', 'strawberry']


'strawberry'

The following codes combine negative indexing and slice indexing

In [68]:
allFruits[-3:]       # Start from the third last item to the end of the list

['pear', 'kiwi', 'strawberry']

In [69]:
allFruits[-3:-1]     # Start from the third last item to the second last item of the list

['pear', 'kiwi']

**Reference copy of a list:**

For list, the assignment operator `=` only copy the address of the source. This means that it is *pointing* or *referencing* to the same object as the source. 

For example:

In [70]:
colors1 = ["red", "green"]
colors2 = colors1
print('colors1 = ', colors1)
print('colors2 = ', colors2)

colors1 =  ['red', 'green']
colors2 =  ['red', 'green']


The above results in the following structure:

![shallowcopy1](https://raw.githubusercontent.com/kalngyk/repoman/master/referencecopy.png)

Since they point to the same list, any changes to either `color1` or `color2` would affect the other.

In [71]:
print('Changing colors2 second element to blue')
colors2[1] = 'blue'            # changing the content of the second item in colors2

print ('colors1 = ', colors1)  # colors1 changes too because of shallow copy
print ('colors2 = ', colors2)

Changing colors2 second element to blue
colors1 =  ['red', 'blue']
colors2 =  ['red', 'blue']


**Shallow copy of a list:**

The method `.copy()` performs a shallow copy where only the content of the shallowest level are copied. 

In [72]:
list1 = ['a', 'b', ['ab', 'ba']]    # list is shallow - contains only one level
list2 = list1.copy()                # copy list
print(list1)
print(list2)

['a', 'b', ['ab', 'ba']]
['a', 'b', ['ab', 'ba']]


The above command results in the following structure:

![shallowcopy](https://raw.githubusercontent.com/kalngyk/repoman/master/shallowcopy.png)

From the figure, it is easy to see why changing the content of the shallow items of one array would not have affect the other array. But, any changes to non-shallow items will affect both arrays

In [74]:
list2[1] = 'x'      # changing a shallow item in list 2  will not affect list1
list2[2][1] = 'zz'  # changing a non-shallow item in list2 will also affect list1
print(list1)
print(list2)

['a', 'b', ['ab', 'zz']]
['a', 'x', ['ab', 'zz']]


**Deep copy of list:**

To copy the entire structure, we can use the module function `copy.deepcopy`.

In [ ]:
from copy import deepcopy

lst1 = ['a','b',['ab','ba']]
lst2 = deepcopy(lst1)   # slice copying


In [76]:
lst2[0] = 'c'
lst2[2][1] = 'd'
print('lst1: ', lst1)
print('lst2: ', lst2)

lst1:  ['a', 'b', ['ab', 'ba']]
lst2:  ['c', 'b', ['ab', 'd']]


### List comparison
There are two operators for comparison in Python: `==` and `is`. 

The operator `is` checks if two variables are referencing the same list or object, while the operator `==` checks if the lists have the same content.

For *reference copy*, both `is` and `==` return `True` because they references the same list or object.

In [77]:
a = [1, 2, 3]
b = a
print(b is a)
print(b == a)

True
True


For *shallow copy* and *deep copy*,
* `is` returns `False` because they are pointing to different lists or objects.
* `==` returns `True` because their content are the same.

In [78]:
b = a.copy()
print(b is a)
print(b == a)

False
True


In [79]:
from copy import deepcopy
c = deepcopy(a)
print(b is a)
print(b == a)

False
True


### Quick reference to useful functions for list

**`list.append(x)`**: Add an item to the end of the list; equivalent to `a[len(a):] = [x]`<br>
**`list.extend(x)`**: Extend the list by appending all the items in the given list; equivalent to `a[len(a):] = L`.<br>
**`list.insert(i, x)`**: Insert the item x at position i. The first argument is the index of the element before which to insert, so `a.insert(0, x)` inserts at the front of the list, and `a.insert(len(a), x)` is equivalent to `a.append(x)`.<br>
**`list.remove(x)`**: Remove the first item from the list whose value is `x` . It is an error if there is no such item.<br>
**`list.pop(i)`**: Remove the item at the given position in the list, and return it. If no index is specified, `a.pop()` removes and returns the last item in the list.<br>
**`list.index(x)`**: Return the index in the list of the first item whose value is `x`. It is an error if there is no such item.<br>
**`List.count(x)`**: Return the number of times `x` appears in the list.<br>
**`list.sort(key=None, reverse=False)`**: Sort the items of the list in place.<br>
**`list.reverse()`**: Reverse the elements of the list, in place.<br>
**`len(list)`**: Returns the number of items in the sequence.<br>
**`min(list)`**: Returns the smallest item in the sequence.<br>
**`max(list)`**: Returns the biggest item in the sequence.<br>
**`any(list)`**: Returns `True` if there exists an item in the sequence which is `True`.<br>
**`all(list)`**: Returns `True` if all items in the seuqnece are True.<br>


---
## Tuple

A tuple is a data structure that is similar to the list except that it is immutable once it is created, i.e., you cannot change its content once created. It takes up less memory for the same number of items compared to list. So, it is advisable to use tuples compared to list if possible. 

To **create a tuple**, use a parentheses rather than a square brackets.

In [80]:
pair = (3,5)
print(pair)
print(pair[0])

(3, 5)
3


The attempt to modify an immutable structure will raise an exception. Exceptions indicate errors: index out of bounds errors, type errors, and so on will all report exceptions in this way.

In [81]:
pair[1] = 6

TypeError: ignored

---
## Set

A set is like a list, but allows **no duplicate items**. Common set operations (difference, intersection, union) are available for the data structure.

**Create a new set from list**:

In [82]:
user_selected_shapes = ['circle', 'square', 'triangle', 'circle']
shapes = set(user_selected_shapes)
shapes

{'circle', 'square', 'triangle'}

**Insert new items into a set**:

In [83]:
print("Adding pentagon")
shapes.add('pentagon') 
print(shapes)
print("Adding circle")
shapes.add('circle')
print(shapes)
print("Adding triangle")
shapes.add('triangle')
print(shapes)



Adding pentagon
{'pentagon', 'circle', 'square', 'triangle'}
Adding circle
{'pentagon', 'circle', 'square', 'triangle'}
Adding triangle
{'pentagon', 'circle', 'square', 'triangle'}


**Check if exist in set**:

In [84]:
if 'circle' in shapes:
    print('circle exists in shapes')
else:
    print('circle does not exist in shapes')
    
if 'rhombus' in shapes:
    print('rhombus exists in shapes')
else:
    print('rhombus does not exist in shapes')
    

circle exists in shapes
rhombus does not exist in shapes


**Operations on set**:

The following shows how to perform intersection (`&`), union (`|`) and deletion (`-`) operation on two sets.

In [85]:
polygons = set(['triangle', 'square', 'hexagon', 'pentagon'])
print ('shapes:   ', shapes)
print ('polygons: ', polygons)
print ()

print('shapes minus polygons:', shapes - polygons)
print('shapes intersect polygons:', shapes & polygons)
print('shapes union polygons:', shapes | polygons)

shapes:    {'pentagon', 'circle', 'square', 'triangle'}
polygons:  {'pentagon', 'square', 'hexagon', 'triangle'}

shapes minus polygons: {'circle'}
shapes intersect polygons: {'pentagon', 'square', 'triangle'}
shapes union polygons: {'square', 'hexagon', 'pentagon', 'circle', 'triangle'}


---
## Dictionary

The dictionary is arguably the second most commonly used data structure in Python. A dictionary stores a map from one type of object (the `key`) to another (the `value`). 
* The `key` must be of an immutable type (string, number, or tuple). 
* The `value` can be of any Python data type (objects, lists, dictionaries, etc).



**Creating a dictionary**:

There are many ways to create a dictionary. 
The standard way is to use the curly bracket `{}`.

In [86]:
studentIds = {'joe': 10491, 'mary': 10489}
studentIds

{'joe': 10491, 'mary': 10489}

Another way is to pass a list of tuples to the dict constructor:

In [87]:
d1 = dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])
d1

{'guido': 4127, 'jack': 4098, 'sape': 4139}


Yet another way is to pass keyword arguments to the dict constructor:

In [88]:
d2 = dict(sape=4139, guido=4127, jack=4098)
d2

{'guido': 4127, 'jack': 4098, 'sape': 4139}

Lastly, you can also use two different lists, one for keys and the other for values. Then, we can construct the dictionary using list comprehensions (which we will cover next).

In [89]:
namelist = ['joe', 'mary']
ids = [10491, 10489]
d3 = {name: age for name, age in zip(namelist, ids)}   # list comprehension
d3

{'joe': 10491, 'mary': 10489}


**Indexing an item in dictionary**:

In [90]:
studentIds = {'joe': 42.0, 'mary': 56.0}
print (studentIds)

# accessing the item with key 'mary'
print(studentIds['mary'])


# Changing the item with key 'mary'
studentIds['mary'] = 100
print(studentIds)

{'joe': 42.0, 'mary': 56.0}
56.0
{'joe': 42.0, 'mary': 100}


**Adding an item in dictionary**:

In [91]:
studentIds['ali'] = 92.0
studentIds

{'ali': 92.0, 'joe': 42.0, 'mary': 100}

**The values can be of different types**:

In [92]:
studentIds['joe'] = 'forty-two'         # string type
print(studentIds)

studentIds['ali'] = [42.0,'forty-two']  # list type
print(studentIds)

{'joe': 'forty-two', 'mary': 100, 'ali': 92.0}
{'joe': 'forty-two', 'mary': 100, 'ali': [42.0, 'forty-two']}


**Getting the size of a dictionary**:

In [93]:
len(studentIds)

3

**Accessing the keys and values in dictionary**:

*(Note that the order of the keys returned may be different from the order in which the keys are created.)*

In [94]:
print(studentIds.keys())
print(studentIds.values())

dict_keys(['joe', 'mary', 'ali'])
dict_values(['forty-two', 100, [42.0, 'forty-two']])


**Converting the dict_keys and dict_values directly to list**:

In [95]:
print(list(studentIds.keys()))
for k in list(studentIds.keys()):
    print(k)

print(list(studentIds.values()))
for v in list(studentIds.values()):
    print(v)

['joe', 'mary', 'ali']
joe
mary
ali
['forty-two', 100, [42.0, 'forty-two']]
forty-two
100
[42.0, 'forty-two']


**Accessing items, keys and values in a dictionary**:

* `<dictionary>.items()` is an iterable object. When used with `for`, it iterates through the list of all *items* in `dictionary`, returning one item at a time. Each item is a tuple  `(key, value)`.
* `<dictionary>.keys()` is an iterable object. When used with `for`, it iterates through the *keys* of all items in `dictionary`, returning one key at a time. 
* `<dictionary>.values()` is an iterable object. When used with `for`, it iterates through the *values* of all items in `dictionary`, returning one value at a time. 

In [96]:
print('All items in studentIds: ')
for item in studentIds.items(): 
    print (item[0], ':', item[1])   # item[0] is the key, item[1] is the value

print('\nThe keys of all items in studentIds: ')
for key in studentIds.keys():
    print (key)

print('\nThe values of all items in studentIds: ')
for value in studentIds.values():
    print (value)

All items in studentIds: 
joe : forty-two
mary : 100
ali : [42.0, 'forty-two']

The keys of all items in studentIds: 
joe
mary
ali

The values of all items in studentIds: 
forty-two
100
[42.0, 'forty-two']


**Removing an item from dictionary**:

In [97]:
del studentIds['joe']
studentIds

{'ali': [42.0, 'forty-two'], 'mary': 100}

As with nested lists, you can also create dictionaries of dictionaries.

---
# Section 4: Advanced constructs
Python allows many advanced constructs. In this section we discuss
- List comprehension
- Function as variable

## List comprehension
List comprehension provides a concise way to operate on a list to create a new list.

Suppose you want to create a list of squares. You might do this as follows:

In [98]:
nums = [1, 3, 5, 7, 11, 13, 17]
squares = []
for n in nums:
    squares.append(n**2)
print(squares)

[1, 9, 25, 49, 121, 169, 289]


List Comprehension can help you represent the loop more concisely as follows:

In [99]:
squares2 = [x**2 for x in nums]
print(squares2)

[1, 9, 25, 49, 121, 169, 289]


You can also do filtering on the items that you want to operate on. Let's say we want to extract only odd numbers from  a list and then multiply all of them by 100:

In [100]:
nums = [1, 2, 3, 4, 5, 6, 7]
result = [x*100 for x in nums if x % 2 == 1]
print (result)

[100, 300, 500, 700]


Another convenient use of list comprehension is to generate a list of pairwise tuples of the original list.

In [101]:
pairs = [(x, y) for x in nums for y in nums]
pairs

[(1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (2, 7),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (3, 7),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6),
 (4, 7),
 (5, 1),
 (5, 2),
 (5, 3),
 (5, 4),
 (5, 5),
 (5, 6),
 (5, 7),
 (6, 1),
 (6, 2),
 (6, 3),
 (6, 4),
 (6, 5),
 (6, 6),
 (6, 7),
 (7, 1),
 (7, 2),
 (7, 3),
 (7, 4),
 (7, 5),
 (7, 6),
 (7, 7)]

Together with functions such as `zip` and `enumerate`, list comprehension allows us to accomplish in a single line some complex operations.

The use of `zip` has been demonstrated in the construction of dictionary, here, we show how `enumerate` allows us to easily obtain the indices of the elements in a list which fulfills a given condition.

In [102]:
nums = [1, 2, 3, 4, 5, 6, 7]
where_odd = [i for (i, y) in enumerate(nums) if y % 2 == 1]
print(where_odd)

[0, 2, 4, 6]


## Function as variable
Functions can be assigned to variables as well as passed as parameters to other functions in Python (similar to function pointers in C/C++).

For instance, Python has an in-built sort function called `sorted` which has the capability to sort a list of **objects** (as opposed to primitive values). The function `sorted` accepts another function as one of its input parameters -- the input function informs `sorted` on how to compute the values to use for sorting.

In this example, we use `sorted` to sort a list of strings by their last two characters.



In [103]:
def last2chars(str):
    return str[-2:]

strings = ["xfile05", "yfile02", "zfile01", "wfile06", "vfile03"]

sorted(strings, key=last2chars)

['zfile01', 'yfile02', 'vfile03', 'xfile05', 'wfile06']

Python allows the definition of unnamed functions through the `lambda` keyword. Using the `lambda`, the above codes can be rewritten as:

In [104]:
sorted(strings, key=lambda x: x[-2:])

['zfile01', 'yfile02', 'vfile03', 'xfile05', 'wfile06']

Together with the `map` and `filter` function, the use of the `lambda` keyword allows us to write concise codes that operate on lists to create new lists. 
This provides an alternative to list comprehension.

For instance, we can create a list which consists of the squared values of another list as follows.

In [105]:
nums = [1, 3, 5, 7, 11, 13, 17]
# The following does the same thing as "squares2 = [x**2 for x in nums]"
squares2 = list(map(lambda x: x**2, nums))
squares2

[1, 9, 25, 49, 121, 169, 289]

We can similarly filter out values from another list as follows.

In [106]:
nums = [1, 2, 3, 4, 5, 6, 7]
# The following does the same thing as "result = [x*100 for x in nums if x % 2 == 1]"
result = list(map(lambda x: x*100, filter(lambda x: x % 2 == 1, nums)))
result

[100, 300, 500, 700]

However, in such cases, the list comprehension way appears to be clearer, and is the preferred method to the creator of Python, Guido Rossum.

---
# Section 5: NumPy

The library module called NumPy is an indispensible part of Python. The module provides an `numpy.ndarray` data structure which is way more powerful than Python lists. It provides simpe calls for

*   data initialization,
*   saving and loading (on disk),
*   search, and 
*   filtering

among many other features.

## Initialization

The following shows how NumPy allows the initializations of various kinds of arrays.




In [107]:
import numpy as np

alist = np.array([1, 2, 3])
print("Array:", alist)

amatrix = np.array([[1, 2, 3], [4, 5, 6]])
print("\nMatrix:")
print(amatrix)

bmatrix = np.zeros((3, 3), dtype=np.float64)
print("\nMatrix initized to zero:")
print(bmatrix)

np.fill_diagonal(bmatrix, 1)
print("\nMatrix with diagonal filled with ones:")
print(bmatrix)

rand_matrix = np.random.random((2, 2))
print("\nMatrix with randomized values:")
print(rand_matrix)

Array: [1 2 3]

Matrix:
[[1 2 3]
 [4 5 6]]

Matrix initized to zero:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matrix with diagonal filled with ones:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matrix with randomized values:
[[0.72791078 0.93207762]
 [0.44890269 0.57049381]]


## Save and load data

The following saves and loads a NumPy data (to and from file). These files have the file extension "npy".

In [108]:
# Creates and saves a matrix of randomized values
rand_matrix = np.random.random((2, 2))
print("Matrix rand_matrix with randomized values:")
print(rand_matrix)
np.save("my_rand_matrix", rand_matrix)

# Change the values of rand_matrix to say, ones
rand_matrix = np.ones((2, 2))
print("\nrand_martix changed to:")
print(rand_matrix)

# Restire the values of rand_matrix
rand_matrix = np.load("my_rand_matrix.npy")
print("\nrand_martix restored:")
print(rand_matrix)

Matrix rand_matrix with randomized values:
[[0.20325869 0.82469528]
 [0.14748461 0.26322858]]

rand_martix changed to:
[[1. 1.]
 [1. 1.]]

rand_martix restored:
[[0.20325869 0.82469528]
 [0.14748461 0.26322858]]


## Searching and Filtering

You can search for values that fulfill a given condition in a NumPy array.

In [109]:
marray = np.array([0.37, 0.82, 0.16, 0.78])
np.where(marray > 0.5)[0]

array([1, 3])

For matrices, the position of every element requires 2 integers to specify (namely, row and column). Hence, the returned value of <tt>np.where</tt> is given in two arrays of equal length: one array gives the rows and the other gives the columns. 

Finally, you an filter out array elements based on the elements' indices. The following example first creates an array of even numbers from 100 to 2, in decreasing order. Then, it finds the indices of the elements which are divisible by 7 and finally, creates a new array with only those elements.

In [110]:
array_of_even_numbers = np.array(range(100, 0, -2))
print("An array of even numbers", array_of_even_numbers)
indices_of_elements_divisible_by_7 = np.where(array_of_even_numbers % 7 == 0)
print("The locations of the elements in the array that are divisible by 7", indices_of_elements_divisible_by_7)
new_array = array_of_even_numbers[indices_of_elements_divisible_by_7]
print("These elements are", new_array)

An array of even numbers [100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]
The locations of the elements in the array that are divisible by 7 (array([ 1,  8, 15, 22, 29, 36, 43]),)
These elements are [98 84 70 56 42 28 14]


# Closing remarks

This tutorial has barely scratched the surface of the features in Python. Python also allows the creation of classes like in C++ or Java, which has not been covered in this tutorial. You are strongly encouraged to go through the following, slightly more complete, tutorials.

- https://docs.python.org/3/tutorial/index.html
- http://cs231n.github.io/python-numpy-tutorial/